version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - react_build:/client/build

  backend:
    build:
      context: ./devsocial_api
      dockerfile: Dockerfile
    command: gunicorn devsocial_api.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/client
    ports:
      - "80:8080"
    depends_on:
      - backend
      - frontend

  db:
   image: postgres:latest
   volumes:
     - db-data:/var/lib/postgresql/data/
   environment:
     - POSTGRES_DB=devsocial_db
     - POSTGRES_USER=kzheng
     - POSTGRES_PASSWORD=${PASSWORD_DB}

volumes:
  react_build:
  db-data:






