services:
  - name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumeMounts:
      - name: react_build
        path: /client/build

  - name: backend
    build:
      context: ./devsocial_api
      dockerfile: Dockerfile
    env:
      - key: DJANGO_SETTINGS_MODULE
        value: "devsocial_api.production"
    envFrom:
      - secret: env-variables
    port: 8000

  - name: nginx
    image: nginx:latest
    mounts:
      - type: BIND
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        readOnly: true
      - name: react_build
        path: /var/www/client
    port: 80

volumes:
  - name: react_build

secrets:
  - name: env-variables
    from:
      - type: env
        name: SECRET_KEY
      - type: env
        name: DATABASE_URL

